# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "runtime-config": "api/beta=false,certificates.k8s.io/v1beta1=true"
      "feature-gates": "AllBeta=false,RotateKubeletClientCertificate=true"
  scheduler:
    extraArgs:
      "feature-gates": "AllBeta=false,RotateKubeletClientCertificate=true"
  controllerManager:
    extraArgs:
      "feature-gates": "AllBeta=false,RotateKubeletClientCertificate=true"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "AllBeta=false,RotateKubeletClientCertificate=true"
