/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	"fmt"
	"sync/atomic"
	time "time"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	clientset "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
	internalinterfaces "k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomResourceDefinitionInformer provides access to a shared informer and lister for
// CustomResourceDefinitions.
type CustomResourceDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CustomResourceDefinitionLister
}

type customResourceDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCustomResourceDefinitionInformer constructs a new informer for CustomResourceDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomResourceDefinitionInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomResourceDefinitionInformer(client, resyncPeriod, indexers, nil)
}

var Delay atomic.Bool

// NewFilteredCustomResourceDefinitionInformer constructs a new informer for CustomResourceDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomResourceDefinitionInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				result, err := client.ApiextensionsV1().CustomResourceDefinitions().List(context.TODO(), options)
				if Delay.Load() {
					fmt.Println("JTL: sleeping CRD list...")
					time.Sleep(5 * time.Second)
					fmt.Println("JTL: continuing CRD list...")
				}
				return result, err
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				w, err := client.ApiextensionsV1().CustomResourceDefinitions().Watch(context.TODO(), options)
				if Delay.Load() {
					fmt.Println("JTL: sleeping CRD watch...")
					time.Sleep(5 * time.Second)
					fmt.Println("JTL: continuing CRD watch...")
				}
				return newDelayingWatcher(w), err
			},
		},
		&apiextensionsv1.CustomResourceDefinition{},
		resyncPeriod,
		indexers,
	)
}

type delayingWatcher struct {
	watcher    watch.Interface
	resultChan <-chan watch.Event
}

func newDelayingWatcher(watcher watch.Interface) watch.Interface {
	source := watcher.ResultChan()
	dest := make(chan watch.Event)
	go func() {
		defer close(dest)
		for e := range source {
			if Delay.Load() {
				fmt.Println("JTL: sleeping CRD watch delivery...")
				time.Sleep(5 * time.Second)
				fmt.Println("JTL: continuing CRD watch delivery...")
			}
			dest <- e
		}
	}()
	return &delayingWatcher{watcher: watcher, resultChan: dest}
}

func (d *delayingWatcher) ResultChan() <-chan watch.Event {
	return d.resultChan
}
func (d *delayingWatcher) Stop() {
	d.watcher.Stop()
}

func (f *customResourceDefinitionInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomResourceDefinitionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customResourceDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiextensionsv1.CustomResourceDefinition{}, f.defaultInformer)
}

func (f *customResourceDefinitionInformer) Lister() v1.CustomResourceDefinitionLister {
	return v1.NewCustomResourceDefinitionLister(f.Informer().GetIndexer())
}
