/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/v2alpha1/generated.proto

package v2alpha1

import (
	fmt "fmt"

	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *EncryptedObject) Reset()      { *m = EncryptedObject{} }
func (*EncryptedObject) ProtoMessage() {}
func (*EncryptedObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_20a9bbdd3d6e7e46, []int{0}
}
func (m *EncryptedObject) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EncryptedObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EncryptedObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedObject.Merge(m, src)
}
func (m *EncryptedObject) XXX_Size() int {
	return m.Size()
}
func (m *EncryptedObject) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedObject.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedObject proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EncryptedObject)(nil), "k8s.io.apiserver.pkg.storage.value.encrypt.envelope.kmsv2.v2alpha1.EncryptedObject")
	proto.RegisterMapType((map[string][]byte)(nil), "k8s.io.apiserver.pkg.storage.value.encrypt.envelope.kmsv2.v2alpha1.EncryptedObject.AnnotationsEntry")
}

func init() {
	proto.RegisterFile("k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/v2alpha1/generated.proto", fileDescriptor_20a9bbdd3d6e7e46)
}

var fileDescriptor_20a9bbdd3d6e7e46 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x31, 0x8f, 0xd3, 0x30,
	0x14, 0xc7, 0xe3, 0x2b, 0x45, 0xc2, 0x6d, 0x45, 0x31, 0x0c, 0xd1, 0x0d, 0x6e, 0x05, 0x4b, 0x17,
	0x6c, 0x51, 0x21, 0x71, 0x62, 0x40, 0x22, 0xba, 0x0c, 0xe8, 0x24, 0x40, 0x19, 0xd9, 0xdc, 0xf6,
	0x91, 0x86, 0xb4, 0xb6, 0xe5, 0x38, 0x91, 0xba, 0xf1, 0x11, 0xd8, 0xf9, 0x20, 0x7c, 0x85, 0x8e,
	0x37, 0xde, 0x54, 0x51, 0xf3, 0x45, 0x50, 0x9d, 0xf4, 0x2e, 0x77, 0x6b, 0xb7, 0xf7, 0xde, 0xff,
	0xef, 0xdf, 0x7b, 0x7e, 0x36, 0xce, 0xf3, 0x8b, 0x82, 0x65, 0x8a, 0xe7, 0xe5, 0x0c, 0x8c, 0x04,
	0x0b, 0x05, 0xaf, 0x40, 0x2e, 0x94, 0xe1, 0x8d, 0x20, 0x74, 0x56, 0x80, 0xa9, 0xc0, 0x70, 0x9d,
	0xa7, 0xbc, 0xb0, 0xca, 0x88, 0x14, 0x78, 0x25, 0x56, 0x25, 0x70, 0x90, 0x73, 0xb3, 0xd1, 0x96,
	0x83, 0xac, 0x60, 0xa5, 0x34, 0xf0, 0x7c, 0x5d, 0x54, 0x53, 0x5e, 0x4d, 0xc5, 0x4a, 0x2f, 0xc5,
	0x1b, 0x9e, 0x82, 0x04, 0x23, 0x2c, 0x2c, 0x98, 0x36, 0xca, 0x2a, 0x12, 0xd5, 0x4c, 0x76, 0xcb,
	0x64, 0x3a, 0x4f, 0x59, 0xc3, 0x64, 0x9e, 0xc9, 0x1a, 0x26, 0x3b, 0x32, 0x99, 0x67, 0xb2, 0x23,
	0xf3, 0xfc, 0x75, 0x9a, 0xd9, 0x65, 0x39, 0x63, 0x73, 0xb5, 0xe6, 0xa9, 0x4a, 0x15, 0xf7, 0xe8,
	0x59, 0xf9, 0xdd, 0x67, 0x3e, 0xf1, 0x51, 0xdd, 0xf2, 0xe5, 0x9f, 0x0e, 0x7e, 0x1a, 0xd7, 0x48,
	0x58, 0x7c, 0x99, 0xfd, 0x80, 0xb9, 0x25, 0xef, 0xf0, 0x00, 0x8e, 0xa5, 0x4b, 0x61, 0x45, 0x78,
	0x36, 0x46, 0x93, 0x7e, 0xf4, 0xcc, 0xed, 0x46, 0x83, 0xb8, 0x2d, 0x24, 0xf7, 0x7d, 0xe4, 0x15,
	0xee, 0xe6, 0xb0, 0xf9, 0x74, 0x19, 0x76, 0xc6, 0x68, 0xf2, 0x24, 0x1a, 0x6c, 0x77, 0xa3, 0xc0,
	0xed, 0x46, 0xdd, 0xab, 0x43, 0x31, 0xa9, 0x35, 0x32, 0xc5, 0x58, 0xaf, 0xca, 0x34, 0x93, 0x9f,
	0xc5, 0x1a, 0xc2, 0x47, 0xde, 0x49, 0x1a, 0x27, 0xfe, 0x7a, 0xab, 0x24, 0x2d, 0x17, 0x79, 0x8b,
	0xfb, 0x77, 0x9d, 0xe2, 0xab, 0xb0, 0xeb, 0x07, 0x1a, 0xba, 0xdd, 0xa8, 0x1f, 0xb7, 0xea, 0xc9,
	0x3d, 0x17, 0xf9, 0x8d, 0x70, 0x4f, 0x48, 0xa9, 0xac, 0xb0, 0x99, 0x92, 0x45, 0xf8, 0x78, 0xdc,
	0x99, 0xf4, 0xa6, 0x0b, 0x76, 0xfa, 0x96, 0xd9, 0x83, 0x95, 0xb1, 0x8f, 0x77, 0x6d, 0x62, 0x69,
	0xcd, 0x26, 0x7a, 0xde, 0xdc, 0xa8, 0xd7, 0x52, 0x92, 0xf6, 0x34, 0xe7, 0x1f, 0xf0, 0xf0, 0xe1,
	0x29, 0x32, 0xc4, 0x9d, 0x1c, 0x36, 0x21, 0x3a, 0x2c, 0x25, 0x39, 0x84, 0xe4, 0x05, 0xee, 0xfa,
	0x89, 0xea, 0x37, 0x48, 0xea, 0xe4, 0xfd, 0xd9, 0x05, 0x8a, 0x96, 0xdb, 0x3d, 0x0d, 0xae, 0xf7,
	0x34, 0xb8, 0xd9, 0xd3, 0xe0, 0xa7, 0xa3, 0x68, 0xeb, 0x28, 0xba, 0x76, 0x14, 0xdd, 0x38, 0x8a,
	0xfe, 0x3a, 0x8a, 0x7e, 0xfd, 0xa3, 0xc1, 0xb7, 0xe8, 0xf4, 0x6f, 0xfa, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x50, 0x57, 0xae, 0x04, 0x03, 0x00, 0x00,
}

func (m *EncryptedObject) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EncryptedObject) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EncryptedObject) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Annotations) > 0 {
		keysForAnnotations := make([]string, 0, len(m.Annotations))
		for k := range m.Annotations {
			keysForAnnotations = append(keysForAnnotations, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForAnnotations)
		for iNdEx := len(keysForAnnotations) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Annotations[string(keysForAnnotations[iNdEx])]
			baseI := i
			if v != nil {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(keysForAnnotations[iNdEx])
			copy(dAtA[i:], keysForAnnotations[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForAnnotations[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.EncryptedDEK != nil {
		i -= len(m.EncryptedDEK)
		copy(dAtA[i:], m.EncryptedDEK)
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.EncryptedDEK)))
		i--
		dAtA[i] = 0x2a
	}
	i -= len(m.PluginName)
	copy(dAtA[i:], m.PluginName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.PluginName)))
	i--
	dAtA[i] = 0x22
	i -= len(m.KeyID)
	copy(dAtA[i:], m.KeyID)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.KeyID)))
	i--
	dAtA[i] = 0x1a
	if m.EncryptedData != nil {
		i -= len(m.EncryptedData)
		copy(dAtA[i:], m.EncryptedData)
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.EncryptedData)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EncryptedObject) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EncryptedData != nil {
		l = len(m.EncryptedData)
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.KeyID)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.PluginName)
	n += 1 + l + sovGenerated(uint64(l))
	if m.EncryptedDEK != nil {
		l = len(m.EncryptedDEK)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.Annotations) > 0 {
		for k, v := range m.Annotations {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = 1 + len(v) + sovGenerated(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *EncryptedObject) String() string {
	if this == nil {
		return "nil"
	}
	keysForAnnotations := make([]string, 0, len(this.Annotations))
	for k := range this.Annotations {
		keysForAnnotations = append(keysForAnnotations, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForAnnotations)
	mapStringForAnnotations := "map[string][]byte{"
	for _, k := range keysForAnnotations {
		mapStringForAnnotations += fmt.Sprintf("%v: %v,", k, this.Annotations[k])
	}
	mapStringForAnnotations += "}"
	s := strings.Join([]string{`&EncryptedObject{`,
		`EncryptedData:` + valueToStringGenerated(this.EncryptedData) + `,`,
		`KeyID:` + fmt.Sprintf("%v", this.KeyID) + `,`,
		`PluginName:` + fmt.Sprintf("%v", this.PluginName) + `,`,
		`EncryptedDEK:` + valueToStringGenerated(this.EncryptedDEK) + `,`,
		`Annotations:` + mapStringForAnnotations + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *EncryptedObject) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EncryptedObject: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EncryptedObject: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedData = append(m.EncryptedData[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedData == nil {
				m.EncryptedData = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PluginName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PluginName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedDEK", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedDEK = append(m.EncryptedDEK[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptedDEK == nil {
				m.EncryptedDEK = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Annotations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Annotations == nil {
				m.Annotations = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthGenerated
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthGenerated
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Annotations[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
